version: '2'
services:
    testjh-app:
        image: testjh
        external_links:
            - testjh-postgresql:postgresql
            - testjh-elasticsearch:elasticsearch
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://postgresql:5432/testJh
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
            - SPRING_DATA_ELASTICSEARCH_CLUSTER_NODES=elasticsearch:9300
        ports:
            - 8080:8080
    testjh-postgresql:
        extends:
            file: postgresql.yml
            service: testjh-postgresql
    testjh-elasticsearch:
        extends:
            file: elasticsearch.yml
            service: testjh-elasticsearch
